version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "npm"
      directory: "/build/builtin"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/build/monaco"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/build/npm/gyp"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/build"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "cargo"
      directory: "/build/win32"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "cargo"
      directory: "/cli"
      schedule:
          interval: "daily"
      versioning-strategy: lockfile-only

    - package-ecosystem: "npm"
      directory: "/extensions/bat"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/clojure"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/coffeescript"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/configuration-editing"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/cpp"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/csharp"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/css-language-features"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/css-language-features/server"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/css"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/dart"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/debug-auto-launch"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/debug-server-ready"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/diff"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/docker"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/emmet"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/extension-editing"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/fsharp"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/git-base"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/git"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/github-authentication"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/github"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/go"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/groovy"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/grunt"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/gulp"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/handlebars"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/hlsl"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/html-language-features"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/html-language-features/server"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/html"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/ini"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/ipynb"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/jake"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/java"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/javascript"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/json-language-features"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/json-language-features/server"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/json"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/julia"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/latex"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/less"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/log"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/lua"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/make"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/markdown-basics"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/markdown-language-features"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/markdown-language-features/server"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/markdown-math"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/media-preview"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/merge-conflict"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/microsoft-authentication"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/notebook-renderers"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/npm"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/objective-c"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/perl"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/php-language-features"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/php"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/powershell"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/pug"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/python"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/r"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/razor"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/references-view"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/restructuredtext"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/ruby"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/rust"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/scss"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/search-result"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/shaderlab"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/shellscript"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/simple-browser"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/sql"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/swift"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-abyss"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-defaults"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-kimbie-dark"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-monokai-dimmed"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-monokai"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-quietlight"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-red"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-seti"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-solarized-dark"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-solarized-light"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/theme-tomorrow-night-blue"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/tunnel-forwarding"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/typescript-basics"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/typescript-language-features"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/vb"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/vscode-api-tests"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/vscode-colorize-tests"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/vscode-test-resolver"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/xml"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/extensions/yaml"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/remote"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/remote/web"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/test/automation"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/test/integration/browser"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/test/leaks"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/test/monaco"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/test/smoke"
      schedule:
          interval: "daily"
      versioning-strategy: increase
